# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 380)
        MainWindow.setMinimumSize(QtCore.QSize(480, 380))
        MainWindow.setMaximumSize(QtCore.QSize(480, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2.addWidget(self.groupBox, 8, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 5)
        self.spinbox_specular_1 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_specular_1.sizePolicy().hasHeightForWidth())
        self.spinbox_specular_1.setSizePolicy(sizePolicy)
        self.spinbox_specular_1.setMaximum(255)
        self.spinbox_specular_1.setObjectName("spinbox_specular_1")
        self.gridLayout_2.addWidget(self.spinbox_specular_1, 7, 0, 1, 1)
        self.checkbox_samevalues = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_samevalues.setObjectName("checkbox_samevalues")
        self.gridLayout_2.addWidget(self.checkbox_samevalues, 6, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 5)
        self.label_texturename = QtWidgets.QLabel(self.centralwidget)
        self.label_texturename.setText("")
        self.label_texturename.setAlignment(QtCore.Qt.AlignCenter)
        self.label_texturename.setObjectName("label_texturename")
        self.gridLayout_2.addWidget(self.label_texturename, 2, 0, 1, 5)
        self.slider_specular_2 = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_specular_2.sizePolicy().hasHeightForWidth())
        self.slider_specular_2.setSizePolicy(sizePolicy)
        self.slider_specular_2.setMaximum(255)
        self.slider_specular_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_specular_2.setObjectName("slider_specular_2")
        self.gridLayout_2.addWidget(self.slider_specular_2, 6, 1, 1, 1)
        self.button_setspecular = QtWidgets.QPushButton(self.centralwidget)
        self.button_setspecular.setObjectName("button_setspecular")
        self.gridLayout_2.addWidget(self.button_setspecular, 7, 3, 1, 2)
        self.slider_specular_1 = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_specular_1.sizePolicy().hasHeightForWidth())
        self.slider_specular_1.setSizePolicy(sizePolicy)
        self.slider_specular_1.setMaximum(255)
        self.slider_specular_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_specular_1.setObjectName("slider_specular_1")
        self.gridLayout_2.addWidget(self.slider_specular_1, 6, 0, 1, 1)
        self.spinbox_specular_2 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_specular_2.sizePolicy().hasHeightForWidth())
        self.spinbox_specular_2.setSizePolicy(sizePolicy)
        self.spinbox_specular_2.setMaximum(255)
        self.spinbox_specular_2.setObjectName("spinbox_specular_2")
        self.gridLayout_2.addWidget(self.spinbox_specular_2, 7, 1, 1, 1)
        self.spinbox_specular_3 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_specular_3.sizePolicy().hasHeightForWidth())
        self.spinbox_specular_3.setSizePolicy(sizePolicy)
        self.spinbox_specular_3.setMaximum(255)
        self.spinbox_specular_3.setObjectName("spinbox_specular_3")
        self.gridLayout_2.addWidget(self.spinbox_specular_3, 7, 2, 1, 1)
        self.button_nexttex = QtWidgets.QPushButton(self.centralwidget)
        self.button_nexttex.setObjectName("button_nexttex")
        self.gridLayout_2.addWidget(self.button_nexttex, 6, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 9, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 9, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 9, 3, 1, 1)
        self.slider_specular_3 = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_specular_3.sizePolicy().hasHeightForWidth())
        self.slider_specular_3.setSizePolicy(sizePolicy)
        self.slider_specular_3.setMaximum(255)
        self.slider_specular_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_specular_3.setObjectName("slider_specular_3")
        self.gridLayout_2.addWidget(self.slider_specular_3, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        self.options_menu = QtWidgets.QMenu(self.menubar)
        self.options_menu.setObjectName("options_menu")
        self.menu_save = QtWidgets.QMenu(self.menubar)
        self.menu_save.setObjectName("menu_save")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_listingpath = QtWidgets.QAction(MainWindow)
        self.action_listingpath.setObjectName("action_listingpath")
        self.action_maszynaroot = QtWidgets.QAction(MainWindow)
        self.action_maszynaroot.setObjectName("action_maszynaroot")
        self.action_savebindings = QtWidgets.QAction(MainWindow)
        self.action_savebindings.setObjectName("action_savebindings")
        self.options_menu.addAction(self.action_listingpath)
        self.options_menu.addAction(self.action_maszynaroot)
        self.menu_save.addAction(self.action_savebindings)
        self.menubar.addAction(self.options_menu.menuAction())
        self.menubar.addAction(self.menu_save.menuAction())

        self.retranslateUi(MainWindow)
        self.slider_specular_2.valueChanged['int'].connect(self.spinbox_specular_2.setValue)
        self.spinbox_specular_2.valueChanged['int'].connect(self.slider_specular_2.setValue)
        self.slider_specular_1.valueChanged['int'].connect(self.spinbox_specular_1.setValue)
        self.spinbox_specular_1.valueChanged['int'].connect(self.slider_specular_1.setValue)
        self.slider_specular_3.valueChanged['int'].connect(self.spinbox_specular_3.setValue)
        self.spinbox_specular_3.valueChanged['int'].connect(self.slider_specular_3.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Wartości predefiniowane"))
        self.checkbox_samevalues.setText(_translate("MainWindow", "Jednakowe wartości"))
        self.button_setspecular.setText(_translate("MainWindow", "Ustaw specular tej teksturze"))
        self.button_nexttex.setText(_translate("MainWindow", "Następna"))
        self.pushButton_2.setText(_translate("MainWindow", "Matowy"))
        self.pushButton.setText(_translate("MainWindow", "Półmatowy"))
        self.pushButton_3.setText(_translate("MainWindow", "Błyszczący"))
        self.options_menu.setTitle(_translate("MainWindow", "Opcje"))
        self.menu_save.setTitle(_translate("MainWindow", "Zapis"))
        self.action_listingpath.setText(_translate("MainWindow", "Wybór folderu roboczego"))
        self.action_maszynaroot.setText(_translate("MainWindow", "Wybór głównego folderu symulatora"))
        self.action_savebindings.setText(_translate("MainWindow", "Zapisz plik z bindingami"))

